// Code generated by genpipe; DO NOT EDIT.
package money

func (p Pipe) Add(x Money) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.Add(x)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}

func (p Pipe) Sub(x Money) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.Sub(x)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}

func (p Pipe) AddPercent(percent int64) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.AddPercent(percent)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}

func (p Pipe) SubtractPercent(percent int64) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.SubtractPercent(percent)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}

func (p Pipe) Mul(factor int64) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.Mul(factor)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}

func (p Pipe) Div(divisor int64) Pipe {
	if p.err != nil {
		return p
	}
	m, err := p.money.Div(divisor)
	if err != nil {
		return Pipe{money: p.money, err: err}
	}
	return Pipe{money: m}
}
